### ISSUE TITLE
Design game interface 🖌👩‍🎨

### ISSUE THREAD

**Issue by hendriku** [M320Trololol/d-fence#1]
We need a mockup from the game interface and its components made with a graphic tool like adobe illustrator. It should show the games concept, the menu/navigation and have to provide the required assets for the 2D rendering.

**Comment by hendriku** [comment]
Okay so as we plan to incrementally extend our games functionalities and its look, I'd suggest to create assets for the following phases:

All the following elements should be in .png format.

Phase 1:
- AppIcon, the logo for our app in standard size
- Background image for the game scenes playground. Size: 2048 × 1536 px
- Loading image which will appear when starting the app. This should be a 2D wallpaper showing the scenery of our game. Size: 2048 × 1536 px
- Menu background. A kind of contrastful border around the menu items. Size: 2048 × 1536 px
- Bullet. Starting with a rock and a slingshot we only need a flying stone for this phase. Size: 32 x 32 px
- Enemies/Zombies (Three different). To be determined via #7.
- Turret/Scout/Treehouse. Feel free to pick your own sizing.

Phase 2:
- The assets for all the weapons, armor or ing general _upgrades_ defined in #6. May be implemented as new scout asset depending on code written.
- Fences. All three types

Phase 3:
- Vary the enemies look even within the same type for a smoother & more creditable appearance.
- Others 2 b determined. See #12

**Comment by bmo-at** [comment]
Background Image for Menu included in afe72e9

**Comment by hendriku** [comment]
Done! ✅
