### ISSUE TITLE
Document with MARK: - Comments 📄🔍

### ISSUE THREAD

**Issue by hendriku** [M320Trololol/d-fence#14]
```
// MARK: - <Modulename>
```
It is important for our evaluation to document the code as suggested.

**Comment by bmo-at** [comment]
How is progress on this?

**Comment by hendriku** [comment]
Nothing yet. :(

**Comment by hendriku** [comment]
We also have to write non MARK comments on some lines. (important vor evaluation)

**Comment by hendriku** [comment]
I am on it. I will document all the code written by myself.

**Comment by hendriku** [comment]
Everything is documented now.
@oliverka Please document the last module (ScoreScene.swift).
