### ISSUE TITLE
Write down game concept 📜

### ISSUE THREAD

**Issue by bmo-at** [M320Trololol/d-fence#2]
The game is a tower defense game where you have to defend against **hoards of something** to protect **something**. 
You only have one rotating turret at the center of the screen that shoots **something**, and you earn more points by killing the **hoards of something** when they are farthest away from the tower. 
As the game progresses, you can buy more and more advanced fences to keep the hoards at bay and earn even more points.

**Comment by bmo-at** [comment]
Suggestions to fill the **somethings** are welcome

**Comment by bmo-at** [comment]
Preliminary draft in ec436e8

**Comment by bmo-at** [comment]
Feedback is highly appreciated

**Comment by hendriku** [comment]
I think the the updated version of the game concept works fine at least until M3. We can add or change things while we develop in an agile way. So I'll close this issue for now. Any suggestions for new features can be made by adding a new issue with the label "suggestion".
