### ISSUE TITLE
Crash on gameOver

### ISSUE THREAD

**Issue by hendriku** [M320Trololol/d-fence#30]
The game crashes on merged-highscores (including newwaves) when I die on Wave 7.
![image](https://user-images.githubusercontent.com/8998518/39663981-7b2cdc4c-507c-11e8-985c-cb3d05752a48.png)
![image](https://user-images.githubusercontent.com/8998518/39664004-e099ed54-507c-11e8-97fe-25edc64b98a7.png)

**Comment by hendriku** [comment]
@oliverka This also happens if I you die on other waves or win the game. Maybe it is because the highscore list is full.

**Comment by oliverka** [comment]
solved bug. There was an ArrayOutOfBounds exception because there was no condition to terminate the for loop. This was the reason why wave 7 crashed after losing the game. So concerning the waves I do not see any problems

**Comment by hendriku** [comment]
Fixed through #32 .
