### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by oliverka** [M320Trololol/d-fence#33]
the app crashes when dying in wave 8 
This is an ArrayOutOfBounds Exception:

<img width="708" alt="bildschirmfoto 2018-05-05 um 22 42 24" src="https://user-images.githubusercontent.com/37831000/39667398-c88c06a0-50b5-11e8-868b-48f473bb1162.png">

**Comment by hendriku** [comment]
Seems like this has been auto-fixed through #32. Not reproducible.
